- become: true
  gather_facts: false
  hosts: all
  name: Prepare
  roles:
  - role: buluma.bootstrap
  - role: buluma.core_dependencies
  - role: buluma.mysql
  - role: buluma.buildtools
  - role: buluma.epel
  - role: buluma.python_pip
  - role: buluma.postgres
